/** Service unit categories — Winners Chapel International Dartford UK intake form. */
export const SERVICE_UNIT_CATALOG = [
  { name: "Children's Church Teachers", description: 'Teach and nurture children during church services.', activities: 'Lesson planning, classroom setup, child engagement, parent handoff.' },
  { name: 'Choir', description: 'Lead the congregation in praise and worship through song.', activities: 'Rehearsals, Sunday ministration, special programmes, voice training.' },
  { name: 'Crowd Control Unit (CCU)', description: 'Manage crowd flow and seating during services and events.', activities: 'Seating coordination, aisle management, overflow areas, event crowd safety.' },
  { name: 'Decoration', description: 'Beautify the sanctuary and event spaces for services.', activities: 'Stage design, floral arrangements, seasonal themes, event décor setup.' },
  { name: 'Elders Team', description: 'Pastoral oversight, counsel, and leadership support for the congregation.', activities: 'Member care, leadership meetings, prayer for the church, mentoring ministers.' },
  { name: 'Harvesters Squad', description: 'Soul-winning and outreach to bring souls into the kingdom.', activities: 'Evangelism outreaches, tract distribution, follow-up coordination, harvest events.' },
  { name: 'Follow-up', description: 'Connect with new converts and visitors after services.', activities: 'Visitor calls, home visits, integration into cell groups, discipleship tracking.' },
  { name: 'Hospitality', description: 'Welcome and care for members and guests with refreshments.', activities: 'Refreshment service, guest reception, event catering, newcomer care.' },
  { name: 'Information Technology (IT)', description: 'Support church systems, networks, and digital infrastructure.', activities: 'Network support, device setup, software troubleshooting, data backups.' },
  { name: 'Maintenance', description: 'Keep church facilities in good working order.', activities: 'Repairs, preventive maintenance, facility inspections, vendor coordination.' },
  { name: 'Media', description: 'Manage visual presentation and media content during services.', activities: 'Slides, lyrics, announcements, video playback, content preparation.' },
  { name: 'Medical', description: 'Provide first aid and health support during church gatherings.', activities: 'First response, health screening events, medical standby at programmes.' },
  { name: 'Parks and Garden', description: 'Maintain outdoor grounds and landscaping.', activities: 'Lawn care, gardening, parking area upkeep, seasonal planting.' },
  { name: 'Prayer Squad', description: 'Intercede for the church, leadership, and congregation.', activities: 'Pre-service prayer, prayer chain, special prayer meetings, altar support.' },
  { name: 'Protocol', description: 'Support dignitaries and ensure orderly service protocol.', activities: 'Guest reception, VIP seating, programme coordination, escort duties.' },
  { name: 'Production', description: 'Coordinate live production elements for services and events.', activities: 'Stage management, run-of-show, rehearsal coordination, production cues.' },
  { name: 'Sales (Bookshop)', description: 'Operate the church bookshop and resource sales.', activities: 'Inventory, sales desk, stock management, new resource promotion.' },
  { name: 'Sanctuary Keepers', description: 'Prepare and maintain the sanctuary before and after services.', activities: 'Altar preparation, cleanliness, communion setup, post-service reset.' },
  { name: 'Security', description: 'Ensure safety and security on church premises.', activities: 'Perimeter patrol, incident response, access control, emergency coordination.' },
  { name: "Teens' Church", description: 'Minister to teenagers with age-appropriate teaching and activities.', activities: 'Teens lessons, mentorship, youth events, parent communication.' },
  { name: 'Technical', description: 'Operate audio, lighting, and technical systems for services.', activities: 'Sound engineering, lighting control, equipment checks, live stream support.' },
  { name: 'Traffic', description: 'Direct vehicle flow in and out of the church premises.', activities: 'Parking guidance, traffic cones, arrival/departure flow, special event routing.' },
  { name: 'Transportation', description: 'Coordinate member transport to and from church programmes.', activities: 'Bus coordination, route planning, driver scheduling, passenger safety.' },
  { name: 'Translation', description: 'Provide language translation during services.', activities: 'Live interpretation, translation equipment, multilingual support teams.' },
  { name: 'Ushering', description: 'Welcome attendees and assist with seating and offerings.', activities: 'Door greeting, offering collection, bulletin distribution, seating assistance.' },
  { name: 'Winning Foundation School', description: 'Disciple new believers through foundational teaching.', activities: 'WSF classes, new convert teaching, graduation tracking, material distribution.' },
] as const;
