-- AlterTable
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "meetingDate" TIMESTAMP(3);
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "maleCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "femaleCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "boysCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "girlsCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "testifiersCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "cell_attendance" ADD COLUMN IF NOT EXISTS "firstTimersCount" INTEGER NOT NULL DEFAULT 0;
